---
- name: Nettoyage awx-operator
  file:
    path: "{{path_awx_tmp}}"
    state: absent
  ignore_errors: yes

- name: Copy Configuration k3s dans "~/.kube"
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /root/.kube/config
    owner: root
    mode: '0600'
    remote_src: yes

- name: Suppression du NS AWX # kubectl delete -n awx --all
  k8s:
    name: awx
    api_version: v1
    kind: Namespace
    state: absent
  ignore_errors: yes

- name: Suppression du NS AWX
  shell: kubectl delete ns awx
  ignore_errors: yes

- name: Supprimer Alias Root
  replace:
    path: "/root/.bashrc"
    regexp: 'kubectl config set-context --current --namespace=awx'
    replace: ''

- name: Purge ancienne config K3S
  shell: "/usr/local/bin/k3s-uninstall.sh"
  ignore_errors: yes